"use client";

import { useActionState } from "react";

import { createCoa, deleteBanner, deleteCoupon, saveBanner, saveBatch, saveCategory, saveCoupon } from "@/features/admin/entities/actions";
import { initialAdminActionState } from "@/features/admin/types";

function Message({state}:{state:{message:string;success:boolean}}){return state.message?<p aria-live="polite" className="admin-form-message" data-success={state.success}>{state.message}</p>:null;}
type CategoryValue={id:string;slug:string;active:boolean;sort_order:number;category_translations:{locale:string;name:string;description:string|null}[]};
export function CategoryForm({value}:{value?:CategoryValue}){const[state,action,pending]=useActionState(saveCategory.bind(null,value?.id??null),initialAdminActionState);const en=value?.category_translations.find(t=>t.locale==="en"),sr=value?.category_translations.find(t=>t.locale==="sr");return <form action={action} className="admin-form admin-form-section"><h2>{value?"Edit category":"Add category"}</h2><div className="admin-form-grid"><label>Name EN<input defaultValue={en?.name} name="nameEn" required /></label><label>Slug<input defaultValue={value?.slug} name="slug" required /></label><label>Name SR<input defaultValue={sr?.name} name="nameSr" /></label><label>Sort order<input defaultValue={value?.sort_order??0} name="sortOrder" type="number" /></label></div><label>Description EN<textarea defaultValue={en?.description??""} name="descriptionEn" rows={3}/></label><label>Description SR<textarea defaultValue={sr?.description??""} name="descriptionSr" rows={3}/></label><label className="admin-checkbox"><input defaultChecked={value?.active} name="active" type="checkbox"/> Active</label><Message state={state}/><button className="admin-button" disabled={pending}>{value?"Save category":"Add category"}</button></form>}
type ProductOption={id:string;slug:string;product_translations:{locale:string;name:string}[]};
type BatchValue={id:string;product_id:string;batch_number:string;manufactured_at:string|null;test_date:string|null;purity:number|null;active:boolean};
export function BatchForm({products,value}:{products:ProductOption[];value?:BatchValue}){const[state,action,pending]=useActionState(saveBatch.bind(null,value?.id??null),initialAdminActionState);return <form action={action} className="admin-form admin-form-section"><h2>{value?"Edit batch":"Add batch"}</h2><div className="admin-form-grid"><label>Product<select defaultValue={value?.product_id??""} name="productId" required><option value="">Select</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_translations.find(t=>t.locale==="en")?.name??p.slug}</option>)}</select></label><label>Batch number<input defaultValue={value?.batch_number} name="batchNumber" required/></label><label>Manufactured<input defaultValue={value?.manufactured_at??""} name="manufacturedAt" type="date"/></label><label>Test date<input defaultValue={value?.test_date??""} name="testDate" type="date"/></label><label>Purity %<input defaultValue={value?.purity??""} max="100" min="0" name="purity" step="0.001" type="number"/></label></div><label className="admin-checkbox"><input defaultChecked={value?.active} name="active" type="checkbox"/> Active</label><Message state={state}/><button className="admin-button" disabled={pending}>{value?"Save batch":"Add batch"}</button></form>}
type BatchOption={id:string;product_id:string;batch_number:string};
export function CoaForm({batches,products}:{batches:BatchOption[];products:ProductOption[]}){const[state,action,pending]=useActionState(createCoa,initialAdminActionState);return <form action={action} className="admin-form admin-form-section"><h2>Upload COA</h2><div className="admin-form-grid"><label>Product<select name="productId" required><option value="">Select</option>{products.map(p=><option key={p.id} value={p.id}>{p.product_translations.find(t=>t.locale==="en")?.name??p.slug}</option>)}</select></label><label>Batch (optional)<select name="batchId"><option value="">Unassigned</option>{batches.map(b=><option key={b.id} value={b.id}>{b.batch_number}</option>)}</select></label><label>Title<input name="title" required/></label><label>PDF<input accept="application/pdf" name="file" required type="file"/></label></div><div className="admin-checks"><label><input name="publicVisible" type="checkbox"/> Public visible</label><label><input name="active" type="checkbox"/> Active</label></div><Message state={state}/><button className="admin-button" disabled={pending}>Upload COA</button></form>}
type CouponValue={id:string;code:string;type:"PERCENTAGE"|"FIXED";value_amount:number|null;percentage_value:number|null;minimum_order_amount:number|null;starts_at:string|null;expires_at:string|null;usage_limit:number|null;active:boolean};
const money=(value:number|null)=>value===null?"":(value/100).toFixed(2);const localDate=(value:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
export function CouponForm({value}:{value?:CouponValue}){const[state,action,pending]=useActionState(saveCoupon.bind(null,value?.id??null),initialAdminActionState);return <form action={action} className="admin-form admin-form-section"><h2>{value?"Edit coupon":"Add coupon"}</h2><div className="admin-form-grid admin-form-grid--four"><label>Code<input defaultValue={value?.code} name="code" required/></label><label>Type<select defaultValue={value?.type??"PERCENTAGE"} name="type"><option>PERCENTAGE</option><option>FIXED</option></select></label><label>Value<input defaultValue={value?(value.type==="FIXED"?money(value.value_amount):value.percentage_value??""):""} name="value" required/></label><label>Minimum order EUR<input defaultValue={value?money(value.minimum_order_amount):""} name="minimum"/></label><label>Starts<input defaultValue={value?localDate(value.starts_at):""} name="startsAt" type="datetime-local"/></label><label>Expires<input defaultValue={value?localDate(value.expires_at):""} name="expiresAt" type="datetime-local"/></label><label>Usage limit<input defaultValue={value?.usage_limit??""} min="1" name="usageLimit" type="number"/></label></div><label className="admin-checkbox"><input defaultChecked={value?.active} name="active" type="checkbox"/> Active</label><Message state={state}/><div className="admin-actions"><button className="admin-button" disabled={pending}>{value?"Save coupon":"Add coupon"}</button>{value?<button className="admin-danger-button" formAction={deleteCoupon.bind(null,value.id)} type="submit">Safe delete</button>:null}</div></form>}
type BannerValue={id:string;key:string;cta_href:string|null;active:boolean;sort_order:number;starts_at:string|null;ends_at:string|null;banner_translations:{locale:string;title:string;body:string|null;cta_label:string|null}[]};
export function BannerForm({value}:{value?:BannerValue}){const[state,action,pending]=useActionState(saveBanner.bind(null,value?.id??null),initialAdminActionState);const en=value?.banner_translations.find(t=>t.locale==="en"),sr=value?.banner_translations.find(t=>t.locale==="sr");return <form action={action} className="admin-form admin-form-section"><h2>{value?"Edit banner":"Add banner"}</h2><div className="admin-form-grid"><label>Key<input defaultValue={value?.key} name="key" required/></label><label>Title EN<input defaultValue={en?.title} name="titleEn" required/></label><label>Title SR<input defaultValue={sr?.title} name="titleSr"/></label><label>CTA href<input defaultValue={value?.cta_href??""} name="ctaHref" placeholder="/en/shop"/></label><label>CTA label EN<input defaultValue={en?.cta_label??""} name="ctaLabelEn"/></label><label>CTA label SR<input defaultValue={sr?.cta_label??""} name="ctaLabelSr"/></label><label>Starts<input defaultValue={value?localDate(value.starts_at):""} name="startsAt" type="datetime-local"/></label><label>Ends<input defaultValue={value?localDate(value.ends_at):""} name="endsAt" type="datetime-local"/></label><label>Sort order<input defaultValue={value?.sort_order??0} name="sortOrder" type="number"/></label><label>Image<input accept="image/avif,image/webp,image/png,image/jpeg" name="image" type="file"/></label></div><label>Body EN<textarea defaultValue={en?.body??""} name="bodyEn" rows={3}/></label><label>Body SR<textarea defaultValue={sr?.body??""} name="bodySr" rows={3}/></label><label className="admin-checkbox"><input defaultChecked={value?.active} name="active" type="checkbox"/> Active</label><Message state={state}/><div className="admin-actions"><button className="admin-button" disabled={pending}>{value?"Save banner":"Add banner"}</button>{value?<button className="admin-danger-button" formAction={deleteBanner.bind(null,value.id)} type="submit">Delete banner</button>:null}</div></form>}
